package com.cimdriver.app.data.local

import android.util.Log
import com.cimdriver.app.data.local.entity.Client
import com.cimdriver.app.data.local.entity.HoursTarget
import com.cimdriver.app.data.local.entity.ProjectCode
import com.cimdriver.app.data.local.entity.Vehicle
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.util.Calendar

object TestDataSeeder {

    suspend fun seedTestData(database: AppDatabase) {
        withContext(Dispatchers.IO) {
            val clientDao = database.clientDao()
            val projectCodeDao = database.projectCodeDao()
            val hoursTargetDao = database.hoursTargetDao()
            val vehicleDao = database.vehicleDao()

            val existingClients = clientDao.getAllClientsSync()
            if (existingClients.isNotEmpty()) {
                Log.d("TestDataSeeder", "Database already contains clients. Skipping seeding.")
                return@withContext
            }

            Log.d("TestDataSeeder", "Seeding test data...")

            // Seed Vehicles
            val existingVehicles = vehicleDao.getAllVehiclesSync()
            var vehicleId = existingVehicles.firstOrNull()?.id
            if (vehicleId == null) {
                vehicleId = vehicleDao.insertVehicle(
                    Vehicle(
                        name = "Test Auto",
                        licensePlate = "AB-123-C",
                        make = "Volkswagen",
                        model = "Golf",
                        year = "2023",
                        odometerStart = 10000,
                        odometerCurrent = 12050,
                        notes = "Test vehicle generated by seeder",
                        usageType = "MIXED",
                        engineType = "ICE"
                    )
                )
            }

            // Seed Clients (which correspond to KLANT addresses)
            val clientId1 = clientDao.insertClient(Client(name = "Google", color = "#4285F4"))
            val clientId2 = clientDao.insertClient(Client(name = "Microsoft", color = "#0F9D58"))

            // Seed Project Codes
            val projectId1 = projectCodeDao.insertProjectCode(ProjectCode(clientId = clientId1, code = "GOOG-DEV", description = "Development for Google", isBillable = true))
            val projectId2 = projectCodeDao.insertProjectCode(ProjectCode(clientId = clientId1, code = "GOOG-CONS", description = "Consultancy for Google", isBillable = true))
            val projectId3 = projectCodeDao.insertProjectCode(ProjectCode(clientId = clientId2, code = "MS-AZURE", description = "Azure migration", isBillable = true))
            val projectId4 = projectCodeDao.insertProjectCode(ProjectCode(clientId = null, code = "INT-ADMIN", description = "Internal administration", isBillable = false))

            // Seed Hours Targets
            val currentYear = Calendar.getInstance().get(Calendar.YEAR)
            
            hoursTargetDao.insertTarget(HoursTarget(clientId = clientId1, projectCodeId = projectId1, name = "Google Dev Q1-Q4", targetHours = 800.0, year = currentYear, color = "#4285F4"))
            hoursTargetDao.insertTarget(HoursTarget(clientId = clientId2, projectCodeId = projectId3, name = "Microsoft Azure Project", targetHours = 400.0, year = currentYear, color = "#0F9D58"))
            hoursTargetDao.insertTarget(HoursTarget(clientId = null, projectCodeId = projectId4, name = "Internal Admin Limit", targetHours = 120.0, year = currentYear, color = "#FF9800"))

            val savedAddressDao = database.savedAddressDao()
            val tripDao = database.tripDao()
            val workDayDao = database.workDayDao()

            // Seed Addresses
            savedAddressDao.insertAddress(com.cimdriver.app.data.local.entity.SavedAddress(label = "Thuis", address = "Amsterdam, Herengracht 1", isHomeLocation = true, addressType = "THUIS"))
            savedAddressDao.insertAddress(com.cimdriver.app.data.local.entity.SavedAddress(label = "Google", address = "Rotterdam, Coolsingel 1", isCustomerLocation = true, addressType = "KLANT", defaultTripType = "BUSINESS", projectCode = "GOOG-DEV"))
            savedAddressDao.insertAddress(com.cimdriver.app.data.local.entity.SavedAddress(label = "Microsoft", address = "Utrecht, Neude 1", isCustomerLocation = true, addressType = "KLANT", defaultTripType = "BUSINESS", projectCode = "MS-AZURE"))

            // Seed Trips
            val now = System.currentTimeMillis()
            val hourMs = 3600 * 1000L
            val dayMs = 24 * hourMs
            val yesterday = now - dayMs
            
            tripDao.insertTrip(com.cimdriver.app.data.local.entity.Trip(
                vehicleId = vehicleId,
                startTime = yesterday - 10 * hourMs,
                endTime = yesterday - 9 * hourMs,
                startAddress = "Amsterdam, Herengracht 1",
                endAddress = "Rotterdam, Coolsingel 1",
                distanceMeters = 75000,
                tripType = "COMMUTE",
                note = "Naar kantoor",
                status = "DONE",
                isManual = false,
                odometerStart = 10000,
                odometerEnd = 10075,
                projectCode = "GOOG-DEV",
                projectCodeId = projectId1
            ))
            
            tripDao.insertTrip(com.cimdriver.app.data.local.entity.Trip(
                vehicleId = vehicleId,
                startTime = yesterday - 5 * hourMs,
                endTime = yesterday - 4 * hourMs,
                startAddress = "Rotterdam, Coolsingel 1",
                endAddress = "Utrecht, Neude 1",
                distanceMeters = 55000,
                tripType = "BUSINESS",
                note = "Klantbezoek Microsoft",
                status = "DONE",
                isManual = false,
                odometerStart = 10075,
                odometerEnd = 10130,
                projectCode = "MS-AZURE",
                projectCodeId = projectId3
            ))
            
            tripDao.insertTrip(com.cimdriver.app.data.local.entity.Trip(
                vehicleId = vehicleId,
                startTime = yesterday - 2 * hourMs,
                endTime = yesterday - 1 * hourMs,
                startAddress = "Utrecht, Neude 1",
                endAddress = "Amsterdam, Herengracht 1",
                distanceMeters = 40000,
                tripType = "BUSINESS",
                note = "Terug naar huis",
                status = "DONE",
                isManual = false,
                odometerStart = 10130,
                odometerEnd = 10170,
                projectCode = "MS-AZURE",
                projectCodeId = projectId3
            ))

            // Seed WorkDay
            val calendar = Calendar.getInstance()
            calendar.timeInMillis = yesterday
            calendar.set(Calendar.HOUR_OF_DAY, 0)
            calendar.set(Calendar.MINUTE, 0)
            calendar.set(Calendar.SECOND, 0)
            val dateStart = calendar.timeInMillis
            
            workDayDao.insertWorkDay(com.cimdriver.app.data.local.entity.WorkDay(
                date = dateStart,
                firstDepartureTime = yesterday - 10 * hourMs,
                arrivalTime = yesterday - 9 * hourMs,
                departureTime = yesterday - 2 * hourMs,
                lastArrivalTime = yesterday - 1 * hourMs,
                roundedArrivalTime = yesterday - 9 * hourMs,
                roundedDepartureTime = yesterday - 2 * hourMs,
                breakMinutes = 45,
                workLocationLabel = "Kantoor Google",
                projectCode = "GOOG-DEV",
                projectCodeId = projectId1,
                status = "TO_REVIEW"
            ))

            Log.d("TestDataSeeder", "Test data seeding completed successfully.")
        }
    }
}

